In [1]:
import tensorflow as tf

In [31]:
tensor = tf.constant([3.0, 4.0, 5.0],tf.float32) # tensor라는 자료형, list 형식
tensor_2 = tf.constant([6.0,7.0,8.0]) # constant에는 텐서에 상수

In [30]:
# tf.cast() 함수를 사용하면 tensor의 자료형을 변환할 수 있음.

In [27]:
tensor_3 = tf.constant([ [1, 2],
                        [3, 4]]) # 2차원 행렬

In [28]:
print(tensor + tensor_2)

tf.Tensor([ 9. 11. 13.], shape=(3,), dtype=float32)


In [22]:
print(tf.add(tensor, tensor_2))

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [20]:
print(tensor)

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


행렬개념을 사용하여 숫자 여러가지를 한번에 계산

-> tensor에서 행렬개념을 사용할 수 있음

In [35]:
w = tf.Variable(1.0) # w값을 나타낼 때 변경이 가능하도록 tf.Variable() 사용

In [36]:
print(w.numpy())

1.0


In [37]:
# w.assign()을 통해 변수에 새로운 값 할당가능
w.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [38]:
w

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>